import Head from 'next/head';
import { useAuth } from '../hooks/useAuth';
import { useVideos } from '../hooks/useVideos';
import styles from '../styles/index.module.css';

export default function Home() {
  const { isLoggedIn, logout } = useAuth();
  const { videos, loading, error } = useVideos();

  if (!isLoggedIn) {
    return null; // Or a loading spinner
  }

  return (
    <div className={styles['home-container']}>
      <Head>
        <title>視聴ロックマン</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles['home-header']}>
        <h1 className={styles['home-title']}>視聴ロックマン</h1>
        <button onClick={logout} className={styles['home-button']}>ログアウト</button>
      </header>

      {loading && <p>動画を読み込み中...</p>}
      {error && <p className={styles['error-message']}>{error}</p>}

      <div className={styles['video-grid']}>
        {videos.map((video) => (
          <div key={video.youtubeVideoId} className={styles['video-card']}>
            <img className={styles['video-thumbnail']} src={video.thumbnailUrl} alt={video.title} />
            <div className={styles['video-info']}>
              <h3 className={styles['video-title']}>{video.title}</h3>
              <p className={styles['channel-title']}>{video.channelTitle}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}