spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:postgresql://localhost:5432/youtube_lockman
        username: user
        password: password
        driver-class-name: org.postgresql.Driver
    data: 
        redis: 
            host: redis
            port: 6379
app:
    jwtSecret: ${JWT_KEY}
    jwtExpirationInMs: 86400000
    youtubeApiKey: ${YOUTUBE_API_KEY}
    
